
# Hugo language configuration
# https://gohugo.io/content-management/multilingual/#configure-languages

title = "Drupal WxT"
languageName = "Français"
weight = 1

[params]
  time_format_default = "2006-01-02"
  time_format_blog = "2006-01-02"
  time_format_releases = "2006-01-02"

[[menu.main]]
  name = "WxT"
  weight = 20
  url = "/docs/"
[[menu.main]]
  name = "GitHub"
  weight = 30
  url = "https://github.com/drupalwxt"
[[menu.main]]
  name = "Télécharger"
  weight = 40
  url = "https://github.com/drupalwxt/wxt/releases"
