# Hugo markup configuration
# https://gohugo.io/getting-started/configuration-markup/

defaultMarkdownHandler = "goldmark"

[goldmark]
  [goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [goldmark.parser]
    attribute = true
    autoHeadingID = true
  [goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false

[highlight]
  codeFences = true
  guessSyntax = "false"
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "tango"
  tabWidth = 4

[tableOfContents]
  endLevel = 6
  startLevel = 1
