# Hugo module configuration
# https://gohugo.io/hugo-modules/

[hugoVersion]
  extended = true
  min = "0.110.0"
[[imports]]
  path = "github.com/google/docsy"
  disable = false
[[imports]]
  path = "github.com/google/docsy/dependencies"
  disable = false
